# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    upload_dir: '%kernel.project_dir%/public/uploads/images'

    app.eav_value_entity_map:
        !php/const App\Entity\ProductAttributeValueText::TYPE: 'App\Entity\ProductAttributeValueText'
        !php/const App\Entity\ProductAttributeValueInt::TYPE: 'App\Entity\ProductAttributeValueInt'
        !php/const App\Entity\ProductAttributeValueImage::TYPE: 'App\Entity\ProductAttributeValueImage'
        !php/const App\Entity\ProductAttributeValueDecimal::TYPE: 'App\Entity\ProductAttributeValueDecimal'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Form\Attribute\Handler\:
        resource: '../src/Form/Attribute/Handler/'
        tags: ['app.attribute_form_handler']

    App\Form\Attribute\Handler\ImageAttributeFormHandler:
        tags: ['app.attribute_form_handler']
        arguments:
            $uploadDir: '%upload_dir%'

    App\Form\Attribute\AttributeFormRegistry:
        arguments:
            $handlers: !tagged_iterator app.attribute_form_handler

    App\Service\Eav\AttributeTypeRegistry:
        arguments:
            $valueEntityMap: '%app.eav_value_entity_map%'

    App\ApiResource\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments:
            $decorated: '@App\ApiResource\OpenApi\OpenApiFactory.inner'
